package com.megazone.ERPSystem_phase3_LogisticsProduction.production.repository.resource_data.materialProduct;

public class MaterialProductRepositoryImpl implements MaterialProductRepositoryCustom{
}
