package com.megazone.ERPSystem_phase3_LogisticsProduction.logistics.repository.product_registration.product;

public class ProductImageRepositoryCustomImpl implements ProductImageRepositoryCustom {

}
