package com.megazone.ERPSystem_phase3_LogisticsProduction.logistics.repository.warehouse_location_management;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class WarehouseLocationRepositoryImpl implements WarehouseLocationRepositoryCustom {
}
