package com.megazone.ERPSystem_phase3_LogisticsProduction.production.repository.resource_data.HazardousMaterial;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class HazardousMaterialRepositoryImpl implements HazardousMaterialRepositoryCustom{
}
